version: "3.8"
services:

  blog:
    build:
      context: .
      args:
        mode: prod
    container_name: blog-api
    restart: always
    ports:
      - 8080:8080
    networks:
      - blog-network
    command: bash -c "./scripts/migrate.sh && ./scripts/runprod.sh"

  nginx:
    image: nginx:alpine
    container_name: blog-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

