"""cascade deleting of roles_permissions

Revision ID: af34812e6bc2
Revises: 33c91b97b7c8
Create Date: 2024-12-01 02:41:10.863872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af34812e6bc2'
down_revision: Union[str, None] = '33c91b97b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_permissions_role_id_fkey', 'roles_permissions', type_='foreignkey')
    op.drop_constraint('roles_permissions_permission_id_fkey', 'roles_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'roles_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'roles_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.create_foreign_key('roles_permissions_permission_id_fkey', 'roles_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key('roles_permissions_role_id_fkey', 'roles_permissions', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
